### ISSUE TITLE
FOUC on initial load

### ISSUE THREAD

**Issue by DBozhinovski** [rbutera/greater-gatsby#1]
It seems that there is a FOUC on every page reload. It's pretty obvious just by running the starter as-is: when you load a page, it first shows it unstyled, and applies styles afterwards. After some poking around, it turned out its due to `gatsby-plugin-styled-components` missing. After adding the plugin, plus some minimal configuration for the plugin, it seems to work fine.

PR incoming :)

**Comment by rbutera** [comment]
Awesome thanks a lot! This was actually an issue I had no idea how to solve
